export const INIT_FIRST_ARTIST = 'INIT_FIRST_ARTIST';
export const INIT_TARGET_ARTIST = 'INIT_TARGET_ARTIST';
export const LOADING_PAUSE = 'LOADING_PAUSE';
export const SET_RELATED_ARTISTS = 'SET_RELATED_ARTISTS'