export const INIT_FIRST_ARTIST = 'INIT_FIRST_ARTIST';
export const INIT_TARGET_ARTIST = 'INIT_TARGET_ARTIST';
export const INIT_FIRST_ARTIST_TRACKS = 'INIT_FIRST_ARTIST_TRACKS';
export const INIT_TARGET_ARTIST_TRACKS = 'INIT_TARGET_ARTIST_TRACKS';
export const RENDER_GAME = 'RENDER_GAME';