export const INIT_FIRST_ARTIST = 'INIT_FIRST_ARTIST';
export const INIT_TARGET_ARTIST = 'INIT_TARGET_ARTIST';
export const SET_CURRENT_ARTIST = 'SET_CURRENT_ARTIST';
export const LOADING_PAUSE = 'LOADING_PAUSE';